version: '3'
services:

  gis-backend:
    ports:
      - 5000:5000
    env_file: .env
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/:/var/opt/gis/:z
    command: gunicorn --config=gunicorn.conf.py --reload server:app

  gis-frontend:
    image: node:latest
    ports:
      - 4200:4200
    working_dir: /app
    volumes:
      - ./Frontend/gis:/app
    command: sh -c "npm install && npm run start:docker"

  crawler:
    image: coronavis-crawler:latest
    build: 
      context: ./Crawler
      dockerfile: Dockerfile
    env_file: .env
    working_dir: /app
    volumes:
      - ./Crawler:/app
    command: ['sh', '-c', 'python crawl_rki_cases.py']

  db:
    image: coronavis/db:latest
    build:
      context: ./Database
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 5432:5432

volumes: 
  gis-db:
    driver: local
