version: '3'
services:

  gis-backend:
    ports:
      - 5000:5000
    env_file: .env
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend/:/var/opt/gis/:z

  gis-frontend:
    image: node:latest
    ports:
      - 4200:4200
    working_dir: /app
    volumes:
      - ./Frontend/gis:/app
    command: sh -c "npm install && npm run start:docker"

  crawler:
    image: python:3-slim
    env_file: .env
    working_dir: /app
    volumes:
      - ./Crawler:/app
    command: ['sh', '-c', 'pip install -r requirements.txt && python crawler.py']

volumes: 
  gis-db:
    driver: local
